[package]
name = "solana-poseidon"
description = "Solana Poseidon hashing"
documentation = "https://docs.rs/solana-poseidon"
version = "5.0.0"
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
all-features = true
rustdoc-args = ["--cfg=docsrs"]

[dependencies]
thiserror = { workspace = true }

[target.'cfg(any(target_os = "solana", target_arch = "bpf"))'.dependencies]
solana-define-syscall = { workspace = true }

[target.'cfg(not(any(target_os = "solana", target_arch = "bpf")))'.dependencies]
ark-bn254 = { workspace = true }
helius-narsil = { git = "https://github.com/Atamanov/helius-narsil.git", rev = "b3d6299009a62dc8906dc94c699219606b383821", features = ["std"] }
light-poseidon = { workspace = true }

[lints]
workspace = true
